os:
  - linux
  - osx

language: java

services:
  - docker
script:
  - mvn test

before_deploy:
  - docker build -t samuelmurray/rest-mash .

deploy:
  provider: script
  script: docker push samuelmurray/rest-mash:latest
  on:
    branch: master